<main>

<h1>Sign-up or Book a room</h1>
<br>
<br>
<form action="<?php echo route_to_url("bookingcustomer"); ?>" method="POST">
 First name:<br>
 <input type="text" name="firstname"><br>
 Last name:<br>
 <input type="text" name="lastname"><br>
 Title:<br>
 <input type="text" name="title"><br>
 Email:<br>
 <input type="text" name="email"><br>
 Address:<br>
 <input type="text" name="address"><br>
 City:<br>
 <input type="text" name="city"><br>
 Country:<br>
 <input type="text" name="country"><br>
 Phone:<br>
 <input type="number" name="phone"><br>
 <input type="submit" name="submit" value="submit">
</form>
<p>


</p>
</main>

<?php

//var_dump($app['view-data']);


 ?>
